---- MODULE MC ----
EXTENDS MCetcdraft, TLC

spec ==
mc_etcdSpecWithReady
----

CONSTANTS
s1, s2, s3
const_InitServer ==
{s1, s2, s3}
----

CONSTANTS
s4, s5
const_Server ==
{s1, s2, s3, s4, s5}
----

CONSTANTS
v1, v2
const_Value ==
{v1, v2}
----

const_ReconfigurationLimit == 
3
----

const_MaxTermLimit == 
6
----

const_MaxTimeoutLimit == 
10
----

const_RequestLimit == 
8
----

const_MaxPendingMsgLimit == 
16
----

const_MaxMsgBufferLimit == 
20
----

const_RestartLimit == 
2
----

const_MaxPartitions == 
2
----

const_PartitionLimit == 
2
----

const_DropLimit == 
6
----

const_DuplicateLimit == 
1
----

const_StepDownLimit == 
3
----

const_HeartbeatLimit == 
12
----

const_SnapshotLimit == 
3
----

const_CompactLimit == 
3
----

const_ConfChangeLimit == 
3
----

const_ReportUnreachableLimit == 
2
----

const_MaxInflightMsgs == 
5
----

symm_3 ==
Permutations(const_InitServer) \union Permutations(const_Server) \union Permutations(const_Value)
====================
\* Generated by tlcwrapper.py on 2026-01-16 22:21:33.934493
