---- MODULE MC ----
EXTENDS MCetcdraft, TLC

spec ==
mc_etcdSpecWithReady
----

CONSTANTS
s1, s2, s3
const_InitServer ==
{s1, s2, s3}
----

const_Server ==
{s1, s2, s3}
----

CONSTANTS
v1, v2
const_Value ==
{v1, v2}
----

const_ReconfigurationLimit == 
1
----

const_MaxTermLimit == 
2
----

const_MaxTimeoutLimit == 
4
----

const_RequestLimit == 
4
----

const_MaxPendingMsgLimit == 
2
----

const_MaxMsgBufferLimit == 
6
----

const_RestartLimit == 
1
----

const_MaxPartitions == 
1
----

const_PartitionLimit == 
1
----

const_DropLimit == 
2
----

const_DuplicateLimit == 
0
----

const_StepDownLimit == 
1
----

const_HeartbeatLimit == 
4
----

const_SnapshotLimit == 
1
----

const_CompactLimit == 
1
----

const_ConfChangeLimit == 
1
----

const_ReportUnreachableLimit == 
1
----

const_MaxInflightMsgs == 
3
----

symm_3 ==
Permutations(const_InitServer) \union Permutations(const_Server) \union Permutations(const_Value)
====================
\* Generated by tlcwrapper.py on 2026-01-21 09:28:48.477917
